version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://app:admin@db:5432/app
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
volumes:
  postgres_data:
