name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 77.92.58.158
          username: admin
          port: 2222
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/piktogram
            git pull origin main
           # docker-compose down --rmi all || true
           # docker-compose up --build -d
            