name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.18.77
          username: karol
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /piktogram
            git pull origin main
            sudo docker-compose up --build -d